name = "singbox-meta-manager"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]

# Configure these as Cloudflare Worker secrets:
# ADMIN_PASSWORD: admin login password
# TOKEN_SECRET: token signing secret

[assets]
directory = "../frontend/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "SINGBOX_DB"
database_name = "singbox_templates_db"
database_id = "2dcf607d-3190-4331-b98e-44ee5509da32"
